### ISSUE TITLE
TLS/SSL connection issue

### ISSUE THREAD

**Issue by panfanbest** [Immortalise/SearchAnything#6]
Hi, thanks for this great project. I am trying to run it on my windows workstation. The environment was set-up successfully. But there is a problem cannot be solved when I ran it (python anything.py). Has anyone had the same issue? or know how to fix it. Thank you!
![image](https://github.com/Immortalise/SearchAnything/assets/67575169/5ddd5c7a-4bcc-4ca1-a738-f35592e79334)

**Comment by Immortalise** [comment]
Hi, it seems that the issue may be due to a connection error with AWS's embedding models. Using a VPN on your computer might help resolve this problem.

**Comment by panfanbest** [comment]
> Hi, it seems that the issue may be due to a connection error with AWS's embedding models. Using a VPN on your computer might help resolve this problem.

Thanks a lot. Now the whole program is running well, and all SLL issues I faced were related to selection of VPNs.
